# Generated by Django 4.1.3 on 2022-11-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('DEGRADED', 'Degraded')], max_length=8)),
                ('image_url', models.CharField(max_length=255)),
                ('announce_date', models.DateField()),
            ],
        ),
    ]
