# Generated by Django 4.1.3 on 2022-11-26 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_boardgame_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='announce_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 17, 42, 55, 900058)),
        ),
    ]
