# Generated by Django 4.1.3 on 2022-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_boardgame_status_alter_boardgame_announce_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=9),
        ),
    ]
