# Generated by Django 4.1.3 on 2022-11-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_boardgame_state_alter_boardgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='state',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Degradado', 'Degradado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Vendido', 'Vendido')], default='DISPONIVEL', max_length=10),
        ),
    ]
