# Generated by Django 4.1.1 on 2022-11-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_boardgame_state_alter_boardgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Vendido', 'Vendido')], default='Disponivel', max_length=10),
        ),
    ]
